
name: Hexo SEO Auto Push

on:
  schedule:
    - cron: 0 4 * * *
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

      - name: 1. 检查url文件
        uses: actions/checkout@master

      - name: 2. 安装 Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: 3. 安装插件
        run: |
          npm init -y
          npm install hexo-seo-autopush

      - name: 4. 自动提交
        run: |
          
          curl -X POST 'https://ssl.bing.com/webmaster/api.svc/json/SubmitUrlBatch?apikey=${{secrets.bing_apikey}}' -H 'Content-Type: application/json' -H 'charset: utf-8' -d @bing.json
          
