name: Release Drafter

on:
  push:
    branches:
      - main # 在 master 分支发生更新时执行此 action

jobs:
  draft_release:
    name: Draft release
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5.20.1
        name: Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
